name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install necessary CI dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 bandit pytest

    - name: Lint with black
      run: |
        black --check backend/  # Check if formatting is correct without modifying files

    - name: Lint with flake8
      run: |
        flake8 backend/

    - name: Run Bandit security checks
      run: |
        bandit -r backend/

    - name: Run tests (if any)
      run: |
        echo "Running tests..."
        pytest backend/  # This will run tests if defined in your 'backend' directory
