name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: your-docker-username  # Replace with your Docker Hub username
        password: your-docker-password  # Replace with your Docker Hub password

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: your-docker-username/throughput-platform:latest  # Replace with your Docker Hub repo

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: your-server-ip  # Replace with the IP or hostname of your remote server
        username: your-ssh-username  # Replace with your SSH username
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # If you prefer to keep SSH keys in secrets, use them here
        script: |
          cd ~/throughput_platform
          git pull
          docker-compose down
          docker-compose up -d --build
