global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
