services:
  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow

  trainer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ../models:/app/models
      - ../data:/app/data
      - ../outputs:/app/outputs

  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.serve
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8501:8501"
    depends_on:
      - mlflow
    volumes:
      - ../models:/app/models
      - ../data:/app/data
      - ../outputs:/app/outputs"
