name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ willisrunner }}  # Use the Docker Hub username secret
        password: ${{ Tl90663802 }}  # Use the Docker Hub password secret

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag willisrunner/5g/general:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push willisrunner/5g/general:latest
